### ISSUE TITLE
Topbar do not work

### ISSUE THREAD

**Issue by Saharash** [DiscordStyles/Fluent#71] opened 2022-06-07 09:10 UTC
Hello, i'm using Fluent on BetterDiscord, already i'm wondering why i'm still in 1.0.5, but the version is now 1.0.8?

The actual bug that i have it's that i can't click on anything at the topbar.

I'm using a plugin for channels, but that only not work with fluent.

i post you a screen on the issue. thanks!
![2022-06-07 11_07_34-Window](https://user-images.githubusercontent.com/34897211/172342634-54930f2d-8578-4736-9bb4-e9bcd3f9f3c9.png)

**Comment by Gibbu** [comment] 2022-10-05 07:42
Just now realized duplicate of #78

**Closed by Gibbu** 2022-10-05 07:42 UTC
Labels: bug, plugin support
